apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==